#Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.
n = int(input('Olá, quer saber a tabuada de qualquer número?\nDigite algum número: '))
print('='*11)
print(n,'X {:2} = {:2}'.format(1, n*1))
print(n,'X {:2} = {:2}'.format(2, n*2))
print(n,'X {:2} = {:2}'.format(3, n*3))
print(n,'X {:2} = {:2}'.format(4, n*4))
print(n,'X {:2} = {:2}'.format(5, n*5))
print(n,'X {:2} = {:2}'.format(6, n*6))
print(n,'X {:2} = {:2}'.format(7, n*7))
print(n,'X {:2} = {:2}'.format(8, n*8))
print(n,'X {:2} = {:2}'.format(9, n*9))
print(n,'X {:2} = {:2}'.format(10,n*10))
print('='*11)
